const fs = require("fs");
const path = require("path");

const q = (id, section, question, options, answer, difficulty, topic, subtopic, explanation, extra = {}) => ({
  id,
  section,
  question,
  options,
  answer,
  difficulty,
  topic,
  subtopic,
  explanation,
  marks: section === "pk" ? 2 : 1,
  ...extra,
});

const questions = [
  // ===== PK 1-25 =====
  q(1, "pk", "Which of the following is a DML command?", { A: "CREATE", B: "SELECT", C: "DROP", D: "ALTER" }, "B", "Easy", "DBMS", "SQL Commands", "SELECT is Data Manipulation Language (DML). CREATE/DROP/ALTER are DDL."),
  q(2, "pk", "A Primary Key must be:", { A: "NULL allowed", B: "Unique and NOT NULL", C: "Duplicate allowed", D: "Always optional" }, "B", "Easy", "DBMS", "Keys", "Primary Key uniquely identifies a row and cannot be NULL."),
  q(3, "pk", "Which clause filters individual rows in SQL?", { A: "HAVING", B: "WHERE", C: "ORDER BY", D: "GROUP BY" }, "B", "Easy", "DBMS", "SQL Clauses", "WHERE filters rows before grouping. HAVING filters groups."),
  q(4, "pk", "Which clause filters groups after aggregation?", { A: "WHERE", B: "HAVING", C: "FROM", D: "JOIN" }, "B", "Medium", "DBMS", "SQL Clauses", "HAVING filters groups created by GROUP BY."),
  q(5, "pk", "In ACID, Atomicity means:", { A: "Permanent storage", B: "All or nothing transaction", C: "High speed", D: "UI style" }, "B", "Easy", "DBMS", "ACID", "Atomicity = transaction fully commits or fully rolls back."),
  q(6, "pk", "3NF mainly removes:", { A: "Partial dependency", B: "Transitive dependency", C: "Atomicity issues", D: "NULL values" }, "B", "Medium", "DBMS", "Normalization", "Third Normal Form eliminates transitive dependencies."),
  q(7, "pk", "A program in execution is called a:", { A: "File", B: "Process", C: "Folder", D: "Port" }, "B", "Easy", "Operating Systems", "Process Management", "A process is a program currently in execution."),
  q(8, "pk", "Round Robin scheduling uses:", { A: "Priority only", B: "Time quantum", C: "Random selection", D: "Longest job first" }, "B", "Easy", "Operating Systems", "CPU Scheduling", "RR gives each ready process a fixed time slice (quantum)."),
  q(9, "pk", "A page fault means:", { A: "Page already in RAM", B: "Required page must be loaded from disk", C: "Page is deleted", D: "Page is printed" }, "B", "Medium", "Operating Systems", "Memory Management", "Page fault occurs when the needed page is not in main memory."),
  q(10, "pk", "The kernel is:", { A: "A user application", B: "The core of the operating system", C: "A web browser", D: "A modem" }, "B", "Easy", "Operating Systems", "OS Basics", "Kernel is the central component of an OS."),
  q(11, "pk", "TCP is best described as:", { A: "Connectionless", B: "Reliable and connection-oriented", C: "Physical layer only", D: "Always same as UDP" }, "B", "Easy", "Computer Networks", "TCP/IP", "TCP provides reliable, ordered, connection-oriented delivery."),
  q(12, "pk", "A router primarily works at which OSI layer?", { A: "Physical", B: "Data Link", C: "Network", D: "Session" }, "C", "Easy", "Computer Networks", "Devices", "Routers forward packets using IP addresses (Network layer)."),
  q(13, "pk", "Default HTTPS port is:", { A: "80", B: "443", C: "21", D: "25" }, "B", "Easy", "Computer Networks", "Ports", "HTTPS uses TCP port 443; HTTP uses 80."),
  q(14, "pk", "DNS mainly converts:", { A: "MAC to IP", B: "Domain name to IP address", C: "File to HTML", D: "Cookie to session" }, "B", "Easy", "Computer Networks", "DNS", "DNS resolves human-readable domain names to IP addresses."),
  q(15, "pk", "Which data structure follows LIFO?", { A: "Queue", B: "Stack", C: "Array only", D: "Graph only" }, "B", "Easy", "Data Structures", "Stack", "Stack = Last In First Out (push/pop at top)."),
  q(16, "pk", "Which data structure follows FIFO?", { A: "Stack", B: "Queue", C: "Tree only", D: "Hash only" }, "B", "Easy", "Data Structures", "Queue", "Queue = First In First Out."),
  q(17, "pk", "Usually the first SDLC phase is:", { A: "Coding", B: "Requirement analysis", C: "Deployment", D: "Testing" }, "B", "Easy", "Software Engineering", "SDLC", "SDLC starts with gathering/analyzing requirements."),
  q(18, "pk", "HTML mainly provides:", { A: "Style", B: "Structure/content", C: "Database storage", D: "Operating system" }, "B", "Easy", "Web Technologies", "HTML", "HTML defines structure; CSS styles; JS adds behaviour."),
  q(19, "pk", "SaaS stands for:", { A: "Software as a Service", B: "System as Storage", C: "Switch as Server", D: "None of these" }, "A", "Easy", "Cloud Computing", "Service Models", "SaaS delivers software over the internet (e.g., web apps)."),
  q(20, "pk", "AES is typically a:", { A: "Symmetric encryption algorithm", B: "Asymmetric-only algorithm", C: "Hash-only function", D: "Computer virus" }, "A", "Medium", "Cyber Security", "Encryption", "AES uses the same key for encryption and decryption (symmetric)."),
  q(21, "pk", "Phishing is:", { A: "A water sport", B: "Fraudulent messages to steal information", C: "A firewall type", D: "A backup method" }, "B", "Easy", "Cyber Security", "Attacks", "Phishing tricks users (fake mails/links) to reveal secrets like OTP."),
  q(22, "pk", "IaaS mainly provides:", { A: "Only email UI", B: "Infrastructure such as VMs and storage", C: "Only painting tools", D: "Only keyboards" }, "B", "Medium", "Cloud Computing", "Service Models", "IaaS = virtual machines, networks, storage on demand."),
  q(23, "pk", "Core Banking Solution (CBS) means:", { A: "Only one branch ledger", B: "Centralized banking accessible from channels/branches", C: "Banking without computers", D: "Cash-only banking" }, "B", "Easy", "Banking IT", "CBS", "CBS centralizes customer accounts for anytime-anywhere access."),
  q(24, "pk", "UPI is mainly used for:", { A: "Instant mobile payments", B: "Yearly settlement only", C: "Printing passbooks only", D: "Cooling servers" }, "A", "Easy", "Banking IT", "Payments", "UPI enables instant account-to-account mobile payments."),
  q(25, "pk", "KYC means:", { A: "Know Your Customer", B: "Keep Your Cash", C: "Kill Your Code", D: "None of these" }, "A", "Easy", "Banking IT", "Compliance", "KYC is identity verification of customers."),

  // ===== ENGLISH 26-50 =====
  q(26, "english", "Find the error: Neither of the boys / are / late.", { A: "Neither of the boys", B: "are", C: "late", D: "No error" }, "B", "Easy", "Grammar", "Subject-Verb Agreement", "Neither is singular → use 'is', not 'are'."),
  q(27, "english", "Find the error: He is senior / than / me.", { A: "He is senior", B: "than", C: "me", D: "No error" }, "B", "Easy", "Grammar", "Prepositions", "Correct usage: senior to (not than)."),
  q(28, "english", "Find the error: She congratulated me / for / my win.", { A: "She congratulated me", B: "for", C: "my win", D: "No error" }, "B", "Easy", "Grammar", "Prepositions", "Congratulate someone on something."),
  q(29, "english", "Find the error: The news / are / good.", { A: "The news", B: "are", C: "good", D: "No error" }, "B", "Easy", "Grammar", "Subject-Verb Agreement", "'News' is singular → 'is'."),
  q(30, "english", "Find the error: One of my friends / live / here.", { A: "One of my friends", B: "live", C: "here", D: "No error" }, "B", "Easy", "Grammar", "Subject-Verb Agreement", "'One of' takes singular verb → 'lives'."),
  q(31, "english", "Find the error: I look forward / to meet / you.", { A: "I look forward", B: "to meet", C: "you", D: "No error" }, "B", "Medium", "Grammar", "Gerunds", "Look forward to + gerund → 'to meeting'."),
  q(32, "english", "Find the error: She is good / in / English.", { A: "She is good", B: "in", C: "English", D: "No error" }, "B", "Easy", "Grammar", "Prepositions", "Good at a subject/skill."),
  q(33, "english", "Success depends ___ hard work.", { A: "on", B: "at", C: "for", D: "with" }, "A", "Easy", "Grammar", "Prepositions", "Depends on is the correct collocation."),
  q(34, "english", "She has been here ___ Monday.", { A: "since", B: "for", C: "from", D: "by" }, "A", "Easy", "Grammar", "Tenses/Prepositions", "Since + point of time; for + duration."),
  q(35, "english", "I prefer tea ___ coffee.", { A: "than", B: "to", C: "from", D: "by" }, "B", "Easy", "Grammar", "Prepositions", "Prefer X to Y."),
  q(36, "english", "He is junior ___ me.", { A: "than", B: "to", C: "from", D: "with" }, "B", "Easy", "Grammar", "Prepositions", "Junior/senior/prefer → to."),
  q(37, "english", "He was ___ tired that he slept.", { A: "so", B: "such", C: "very", D: "too" }, "A", "Easy", "Grammar", "Conjunctions", "So + adjective + that."),
  q(38, "english", "___ honest man is respected.", { A: "A", B: "An", C: "The", D: "No article" }, "B", "Easy", "Grammar", "Articles", "Honest starts with vowel sound → An."),
  q(
    39,
    "english",
    "What is the main idea of the passage?",
    {
      A: "Ignore security completely",
      B: "Digital banking needs strong security and customer awareness",
      C: "Always share OTP with agents",
      D: "Banks should stop digital services",
    },
    "B",
    "Easy",
    "Reading Comprehension",
    "Main Idea",
    "Passage stresses cybersecurity, MFA/encryption, and alert customers under regulation.",
    {
      context_group: "passage_digital_banking_security",
      context:
        "Directions (Q39–Q40): Read the passage carefully.\n\nDigital banking needs strong cybersecurity. Phishing and OTP fraud are rising. Encryption and MFA help. Customers must stay alert. Regulators push compliance.",
    }
  ),
  q(
    40,
    "english",
    "According to safe banking practice highlighted in the passage theme, OTP should be:",
    {
      A: "Shared always with callers",
      B: "Never shared",
      C: "Posted on social media",
      D: "Ignored completely as useless",
    },
    "B",
    "Easy",
    "Reading Comprehension",
    "Detail/Inference",
    "OTP fraud is rising; OTP must never be shared.",
    { context_group: "passage_digital_banking_security" }
  ),
  q(41, "english", "Choose the correct replacement for: discuss about", { A: "discuss", B: "discuss on", C: "discussing about", D: "No change" }, "A", "Easy", "Grammar", "Phrase Replacement", "'Discuss' does not take 'about'."),
  q(42, "english", "Choose the correct replacement for: more taller", { A: "taller", B: "most taller", C: "more tallest", D: "No change" }, "A", "Easy", "Grammar", "Phrase Replacement", "Avoid double comparative; use taller."),
  q(43, "english", "Choose the correct replacement for: return back", { A: "return", B: "give back again", C: "returned back", D: "No change" }, "A", "Easy", "Grammar", "Phrase Replacement", "'Return' already means give back; 'back' is redundant."),
  q(44, "english", "Choose the correct replacement for: capable to", { A: "capable of", B: "capable for", C: "capable in", D: "No change" }, "A", "Easy", "Grammar", "Phrase Replacement", "Capable of + gerund/noun."),
  q(45, "english", "Phishing means:", { A: "Fraud to steal information", B: "A sport", C: "A loan product", D: "A printer error" }, "A", "Easy", "Vocabulary", "Banking/IT Vocab", "Phishing = deceptive attempt to steal credentials/data."),
  q(46, "english", "Encrypt means:", { A: "Code/hide data", B: "Delete data", C: "Print data", D: "Ignore data" }, "A", "Easy", "Vocabulary", "IT Vocab", "Encryption converts data into unreadable form."),
  q(47, "english", "Obsolete means:", { A: "Outdated", B: "New", C: "Fast", D: "Bright" }, "A", "Easy", "Vocabulary", "Synonyms", "Obsolete = no longer in use / outdated."),
  q(48, "english", "Lucid means:", { A: "Clear", B: "Dark", C: "Confused", D: "Angry" }, "A", "Easy", "Vocabulary", "Synonyms", "Lucid = clear and easy to understand."),
  q(49, "english", "Fraud means:", { A: "Honesty", B: "Cheating/deception", C: "A gift", D: "A holiday" }, "B", "Easy", "Vocabulary", "Banking Vocab", "Fraud = wrongful deception for gain."),
  q(50, "english", "Fix the sentence: He don't know.", { A: "doesn't know", B: "didn't knew", C: "not know", D: "No change" }, "A", "Easy", "Grammar", "SVA", "He/She/It → doesn't know."),

  // ===== REASONING 51-75 =====
  q(51, "reasoning", "Statements: A ≥ B > C = D. Conclusion: A > D. Does it follow?", { A: "Follows", B: "Does not follow", C: "Either follows", D: "Data inadequate" }, "A", "Easy", "Inequality", "Direct Relation", "A ≥ B > C = D ⇒ A > D."),
  q(52, "reasoning", "Statements: P < Q ≤ R. Conclusion: P < R. Does it follow?", { A: "Follows", B: "Does not follow", C: "Either", D: "None" }, "A", "Easy", "Inequality", "Direct Relation", "P < Q ≤ R ⇒ P < R."),
  q(53, "reasoning", "Codes: @ means >, # means <, & means =. Statement: X @ Y # Z. Conclusion: X > Z. Does it follow?", { A: "Follows", B: "Does not follow", C: "Either", D: "None" }, "B", "Medium", "Coded Inequality", "Broken Chain", "X > Y < Z → relation between X and Z is not definite."),
  q(54, "reasoning", "If BAT is coded as CBU (+1 each letter), then SUN is coded as:", { A: "TVO", B: "TVM", C: "RUM", D: "TVN" }, "A", "Easy", "Coding-Decoding", "Letter Shift", "S→T, U→V, N→O ⇒ TVO."),
  q(55, "reasoning", "Using opposite letters (A↔Z, B↔Y, …), FISH is coded as:", { A: "URHS", B: "GJTI", C: "EHRG", D: "UFIR" }, "A", "Medium", "Coding-Decoding", "Opposite Letters", "F↔U, I↔R, S↔H, H↔S ⇒ URHS."),
  q(56, "reasoning", "Sum of positional values of ACE (A=1, B=2, …) is:", { A: "6", B: "9", C: "8", D: "12" }, "B", "Easy", "Coding-Decoding", "Position Values", "A+C+E = 1+3+5 = 9."),
  q(57, "reasoning", "All pens are books. All books are red. Conclusion: All pens are red.", { A: "Follows", B: "Does not follow", C: "Either", D: "None" }, "A", "Easy", "Syllogism", "All-All", "All pens ⊆ books ⊆ red ⇒ all pens are red."),
  q(58, "reasoning", "All A are B. Some B are C. Conclusion: Some A are C.", { A: "Follows", B: "Does not follow", C: "Either", D: "None" }, "B", "Medium", "Syllogism", "All+Some", "Some B are C need not include A; not definite."),
  q(59, "reasoning", "Some dogs are cats. All cats are animals. Conclusion: Some dogs are animals.", { A: "Follows", B: "Does not follow", C: "Either", D: "None" }, "A", "Easy", "Syllogism", "Some+All", "Dogs overlapping cats that are animals ⇒ some dogs are animals."),
  q(60, "reasoning", "A person walks 6 km South, turns right, walks 8 km. Distance from start?", { A: "10 km", B: "14 km", C: "2 km", D: "48 km" }, "A", "Easy", "Direction Sense", "Pythagoras", "Right after South → West. √(6²+8²)=10."),
  q(61, "reasoning", "A is father of B. B is mother of C. How is A related to C?", { A: "Father", B: "Uncle", C: "Grandfather", D: "Brother" }, "C", "Easy", "Blood Relation", "Generations", "B is mother of C, A is father of B ⇒ A is maternal grandfather of C."),
  q(62, "reasoning", "Rank 11th from top and 19th from bottom. Total students?", { A: "29", B: "30", C: "28", D: "31" }, "A", "Easy", "Order & Ranking", "Formula", "Total = 11 + 19 − 1 = 29."),
  q(63, "reasoning", "Input: 55 12 40 8 27. Rule: smallest number shifts left each step. Step I is:", { A: "8 55 12 40 27", B: "12 55 40 8 27", C: "55 8 12 40 27", D: "8 12 40 55 27" }, "A", "Medium", "Input-Output", "Number Arrangement", "Smallest 8 moves to left; remaining keep order."),
  q(64, "reasoning", "Same Input-Output: Step II is:", { A: "8 12 55 40 27", B: "8 55 12 40 27", C: "12 8 55 40 27", D: "8 12 27 40 55" }, "A", "Medium", "Input-Output", "Number Arrangement", "Next smallest 12 moves left after 8."),
  q(65, "reasoning", "P left end, T right end, Q immediate right of P, S between Q and R (5 seats). Who is at position 3?", { A: "S", B: "R", C: "Q", D: "T" }, "A", "Medium", "Puzzles", "Linear Seating", "Order: P Q S R T ⇒ position 3 = S."),
  q(66, "reasoning", "In the same linear arrangement, who sits between S and T?", { A: "R", B: "Q", C: "P", D: "None" }, "A", "Medium", "Puzzles", "Linear Seating", "P-Q-S-R-T ⇒ between S and T is R."),
  q(67, "reasoning", "5 floors: Q on 3, P immediately below Q, T on top, R not on 1, S below R. Who is on floor 1?", { A: "S", B: "P", C: "R", D: "Q" }, "A", "Medium", "Puzzles", "Floor Puzzle", "S1-P2-Q3-R4-T5."),
  q(68, "reasoning", "In the same floor puzzle, who is on floor 4?", { A: "R", B: "S", C: "P", D: "Q" }, "A", "Medium", "Puzzles", "Floor Puzzle", "Floor 4 = R."),
  q(69, "reasoning", "Codes: 'red is blue'→ka la pa; 'blue and green'→pa sa ta. Code for blue?", { A: "pa", B: "ka", C: "la", D: "sa" }, "A", "Medium", "Coding-Decoding", "Condition Coding", "Common word blue ↔ common code pa."),
  q(70, "reasoning", "Also 'green is yellow'→ta ka na. Code for yellow?", { A: "na", B: "ta", C: "ka", D: "pa" }, "A", "Medium", "Coding-Decoding", "Condition Coding", "is=ka, green=ta ⇒ yellow=na."),
  q(71, "reasoning", "Age of A? I: A is 5 years older than B. II: B is 20. Are the data sufficient?", { A: "I alone", B: "II alone", C: "Either I or II alone", D: "Both I and II together" }, "D", "Easy", "Data Sufficiency", "Ages", "Need both: A = 20 + 5 = 25."),
  q(72, "reasoning", "Tallest among P,Q,R? I: P>Q. II: Q>R. Sufficient?", { A: "I alone", B: "II alone", C: "Either alone", D: "Both together" }, "D", "Easy", "Data Sufficiency", "Comparison", "Both ⇒ P > Q > R ⇒ P tallest."),
  q(73, "reasoning", "What day is today? I: Yesterday was Friday. II: Tomorrow is Sunday. Sufficient?", { A: "I alone", B: "II alone", C: "Either I or II alone", D: "Both needed" }, "C", "Easy", "Data Sufficiency", "Calendar", "Either alone ⇒ today is Saturday."),
  q(74, "reasoning", "What is the number? I: It is even. II: It lies between 10 and 14. Sufficient?", { A: "I alone", B: "II alone", C: "Either alone", D: "Both together" }, "D", "Easy", "Data Sufficiency", "Numbers", "Even between 10 and 14 ⇒ 12."),
  q(75, "reasoning", "Distance? I: Speed = 40 km/h. II: Time = 2 hours. Sufficient?", { A: "I alone", B: "II alone", C: "Either alone", D: "Both together" }, "D", "Easy", "Data Sufficiency", "Speed-Distance", "Distance = 40 × 2 = 80 km."),

  // ===== QUANT 76-100 =====
  q(76, "quant", "48 ÷ 8 + 7 × 3 − 5 = ?", { A: "22", B: "20", C: "24", D: "18" }, "A", "Easy", "Simplification", "BODMAS", "6 + 21 − 5 = 22."),
  q(77, "quant", "30% of 400 + 25 = ?", { A: "145", B: "125", C: "155", D: "120" }, "A", "Easy", "Percentage", "Basic %", "0.3×400=120; +25=145."),
  q(78, "quant", "(12 + 8) × 5 ÷ 10 = ?", { A: "10", B: "8", C: "12", D: "15" }, "A", "Easy", "Simplification", "BODMAS", "20×5÷10=10."),
  q(79, "quant", "√196 + 5² − 8 = ?", { A: "31", B: "29", C: "33", D: "25" }, "A", "Easy", "Simplification", "Squares/Roots", "14 + 25 − 8 = 31."),
  q(80, "quant", "36 ÷ 6 + 8 × 2 − 5 = ?", { A: "17", B: "15", C: "19", D: "21" }, "A", "Easy", "Simplification", "BODMAS", "6 + 16 − 5 = 17."),
  q(81, "quant", "49.9 × 2.1 ≈ ?", { A: "105", B: "90", C: "120", D: "80" }, "A", "Easy", "Approximation", "Rounding", "≈50×2.1=105."),
  q(82, "quant", "998 ÷ 4.9 ≈ ?", { A: "200", B: "150", C: "250", D: "180" }, "A", "Easy", "Approximation", "Rounding", "≈1000÷5=200."),
  q(83, "quant", "15% of 402 ≈ ?", { A: "60", B: "50", C: "70", D: "45" }, "A", "Easy", "Approximation", "Percentage", "≈15% of 400 = 60."),
  q(84, "quant", "Series: 3, 6, 12, 24, ?", { A: "48", B: "36", C: "42", D: "30" }, "A", "Easy", "Number Series", "×2 Pattern", "Each term ×2 ⇒ 48."),
  q(85, "quant", "Series: 1, 4, 9, 16, 25, ?", { A: "36", B: "30", C: "49", D: "32" }, "A", "Easy", "Number Series", "Squares", "Perfect squares ⇒ next 36."),
  q(86, "quant", "Series: 2, 6, 12, 20, 30, ?", { A: "42", B: "40", C: "36", D: "44" }, "A", "Easy", "Number Series", "+n Pattern", "Differences +4,+6,+8,+10,+12 ⇒ 42."),
  q(87, "quant", "x²−5x+6=0 and y²−9y+20=0. Relation between x and y?", { A: "x < y", B: "x > y", C: "x = y", D: "Cannot be determined" }, "A", "Medium", "Quadratic Equations", "Compare Roots", "x=2,3; y=4,5 ⇒ x < y."),
  q(88, "quant", "x²−4x+4=0 and y²−4y+4=0. Relation?", { A: "x < y", B: "x > y", C: "x = y", D: "Cannot be determined" }, "C", "Easy", "Quadratic Equations", "Compare Roots", "Both give root 2 ⇒ x = y."),
  q(89, "quant", "x²−7x+12=0 and y²−5y+6=0. Relation?", { A: "x < y", B: "x > y", C: "x = y", D: "Cannot be determined" }, "D", "Medium", "Quadratic Equations", "Compare Roots", "x=3,4; y=2,3 ⇒ relation not unique."),
  q(90, "quant", "Sales: Mon 200, Tue 350, Wed 250, Thu 400, Fri 300. Total sales?", { A: "1500", B: "1400", C: "1600", D: "1200" }, "A", "Easy", "Data Interpretation", "Table Totals", "200+350+250+400+300=1500."),
  q(91, "quant", "Using the same sales data, average daily sales?", { A: "300", B: "250", C: "350", D: "280" }, "A", "Easy", "Data Interpretation", "Average", "1500/5=300."),
  q(92, "quant", "Using the same sales data, highest sales day?", { A: "Thursday", B: "Tuesday", C: "Friday", D: "Monday" }, "A", "Easy", "Data Interpretation", "Comparison", "Thu=400 is maximum."),
  q(93, "quant", "Using the same sales data, Thu − Mon = ?", { A: "200", B: "150", C: "100", D: "250" }, "A", "Easy", "Data Interpretation", "Difference", "400−200=200."),
  q(94, "quant", "A:B = 3:5 and B = 45. Find A.", { A: "27", B: "30", C: "25", D: "36" }, "A", "Easy", "Ratio", "Parts Method", "A=3/5×45=27."),
  q(95, "quant", "SI on ₹4000 at 5% p.a. for 2 years?", { A: "400", B: "200", C: "500", D: "450" }, "A", "Easy", "Simple Interest", "Formula", "SI=(4000×5×2)/100=400."),
  q(96, "quant", "25% of 480 = ?", { A: "120", B: "100", C: "140", D: "96" }, "A", "Easy", "Percentage", "Basic %", "0.25×480=120."),
  q(97, "quant", "CP=500, SP=600. Profit %?", { A: "20%", B: "25%", C: "15%", D: "10%" }, "A", "Easy", "Profit & Loss", "Profit %", "Profit 100; % = 100/500×100=20%."),
  q(98, "quant", "CP=900, Loss=10%. SP=?", { A: "810", B: "890", C: "800", D: "820" }, "A", "Easy", "Profit & Loss", "Loss SP", "SP=900×0.9=810."),
  q(99, "quant", "Average of 4 numbers is 25. Their sum?", { A: "100", B: "50", C: "75", D: "125" }, "A", "Easy", "Average", "Sum Formula", "Sum=25×4=100."),
  q(100, "quant", "1000 decreased by 10%. New value?", { A: "900", B: "990", C: "890", D: "910" }, "A", "Easy", "Percentage", "Decrease", "1000×0.9=900."),
];

const exam = {
  exam: {
    id: "ibps-it-officer-restart-mock-2026-08-20",
    title: "IBPS IT Officer Prelims — Restart Mock (Comeback Day)",
    type: "IBPS SO Scale-I | IT Officer Prelims",
    date: "2026-08-20",
    duration_minutes: 80,
    total_questions: 100,
    total_marks: 125,
    marking: {
      correct: 1,
      wrong: -0.25,
      unattempted: 0,
      note: "PK questions have marks:2 each (25×2=50). Other sections marks:1 each. If your site supports per-question marks, use question.marks. Else net≈ correctCount - 0.25*wrong; for PK score multiply PK correct by 2.",
    },
    sections: [
      { id: "pk", name: "Professional Knowledge", questions: 25, marks: 50 },
      { id: "english", name: "English Language", questions: 25, marks: 25 },
      { id: "reasoning", name: "Reasoning Ability", questions: 25, marks: 25 },
      { id: "quant", name: "Quantitative Aptitude", questions: 25, marks: 25 },
    ],
    suggested_order: ["pk", "english", "reasoning", "quant"],
    questions,
  },
};

const out = path.join(__dirname, "exam_restart_mock_2026-08-20.json");
fs.writeFileSync(out, JSON.stringify(exam, null, 2), "utf8");
console.log("Wrote", out, "questions:", questions.length);
